name: Activity Box

on:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: siksum/activity-box@master
        env:
          GH_PAT: ${{ secrets.GIT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.sikk }}
          GH_USERNAME: siksum
          GIST_ID: ed3e6ebb935e4d683cc1df68fd109806
